### ISSUE TITLE
Tutorial - next next next - should be 14 steps

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico#13]
See video, 13 seconds: https://www.youtube.com/watch?v=3HB_6CIch6w

**Comment by epiqueras** [comment]
You have to place a bid to continue, it says so in the text. I should probably highlight it though, thanks for the feedback. :)

**Comment by stefek99** [comment]
Holy cow!

Of course!

> Place a bid to continue.

Banner blindness, clicking next next next without reading what's on the screen...
