### ISSUE TITLE
Bid - Infinity ETH?

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico#14]
![image](https://user-images.githubusercontent.com/249703/39756343-1b26ab9c-52c1-11e8-807a-7663ed2e0c57.png)

**Comment by epiqueras** [comment]
I think this was fixed in the latest release, I see 99000000....

Are you still having this problem?

**Comment by stefek99** [comment]
I was using a basic IICO contract.

Now I see whitelisting functionality is added... Probably I need to redeploy to be compatible with the UI.

I need to check a few things, will keep you posted.

**Comment by epiqueras** [comment]
No. See this line:
https://github.com/kleros/openiico/blob/91968b5c62c42ec4fac291911d0f296efb73d715/src/containers/iico/components/bids/index.js#L116

**Comment by stefek99** [comment]
Facts: 
* There are `160m` tokens
* Invested `0.1 ETH` 
* Personal cap of `10 ETH`

Currently, I'm the only bidder, all `160m` goes to me, price per token is: 

`0.1 ETH = 100000000000000000 wei`

`100000000000000000 / 160000000 = 625000000 wei = 0.000000000625 ETH`


---

Maximum price per token will be reached when the cap will is reached, at `10 ETH`

My `0.1 ETH` invested at `10 ETH` total, will be `1%` of total supply which is `1.6m` tokens...

`0.1 ETH` buying `1.6m` tokens is... What is the maximum price per token you would pay?

**Comment by epiqueras** [comment]
In the tutorial there is 1 token for sale. So the math works out.

**Comment by stefek99** [comment]
![image](https://user-images.githubusercontent.com/249703/39840822-9f708f18-53d8-11e8-8e7a-02ed4df1467c.png)

Suggestion - use the number of tokens from the actual IICO contract.
