### ISSUE TITLE
Clicking on X does not show bids at the bottom

### ISSUE THREAD

**Issue by stefek99** [kleros/openiico#15]
11 seconds: https://youtu.be/IXR2l3uu2LM

Clicking "skip tutorial" works.

Clicking "X" does not.

**Comment by epiqueras** [comment]
That is intended. You can continue the tutorial by clicking on the purple beacon.

**Comment by stefek99** [comment]
Nitty gritty details...

* skip tutorial
* X
* close

...are the same.

There is no time and no place to educate users how to close popups.

There should be always a way to restore tutorial regardless the way how we closed it.

**Comment by epiqueras** [comment]
> You can continue the tutorial by clicking on the purple beacon.

**Comment by stefek99** [comment]
![image](https://user-images.githubusercontent.com/249703/39840857-c047d188-53d8-11e8-8fc6-e36bd369b2c8.png)

> There is no time and no place to educate users how to close popups.

Do we really want to spend time writing a tutorial to the tutorial?

14 steps: "numer of tokens means number of tokens"

For me - close, X, "skip tutorial" - should mean the same.

Currently pressing X does not show bids, keeps the purple beacon pulsing.

Currently pressing "skip tutorial" shows the bids, does not show the purple beacon.

Do not over-complicate-over-engineer. 

KISS
